### ISSUE TITLE
Unexpected token <

### ISSUE THREAD

**Issue by theqwertman** [webhook/webhook-generate#32]
When running wh deploy on a custom server, I get:

```
Uploading, this might take a minute.undefined:1
<html>
^
SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request._callback (C:\Users\Max\AppData\Roaming\npm\node_modules\wh\lib\push.js:199:21)
    at Request.self.callback (C:\Users\Max\AppData\Roaming\npm\node_modules\wh\node_modules\request\request.js:123:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (C:\Users\Max\AppData\Roaming\npm\node_modules\wh\node_modules\request\request.js:893:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (C:\Users\Max\AppData\Roaming\npm\node_modules\wh\node_modules\request\request.js:844:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

wh serve has no issues

**Comment by budparr** [comment]
I get this intermittently, and it's odd because it will generally go away on subsequent builds, but nothing seems to help consistently, including resetting my running processes on the server. I've done troubleshooting on the server and local files to no avail.

**Comment by theqwertman** [comment]
I just looked into the push.js that is causing the problem. It comes from `JSON.parse`ing a server response that isn't actually JSON. In my case, the response is a 413 error (request entity too large). Adding `client_max_body_size 10M` to the server config in Nginx solved the problem for me.
